CREATE TABLE TBL_MARCA (
  ID_MARCA SERIAL PRIMARY KEY,
  TX_NOME VARCHAR(50) NOT NULL
);

INSERT INTO TBL_MARCA (TX_NOME) VALUES ('Volkswagen');
INSERT INTO TBL_MARCA (TX_NOME) VALUES ('Toyota');
INSERT INTO TBL_MARCA (TX_NOME) VALUES ('Hyundai');
INSERT INTO TBL_MARCA (TX_NOME) VALUES ('Ford');
INSERT INTO TBL_MARCA (TX_NOME) VALUES ('Renault');

