CREATE TABLE TBL_AUTOMOVEL
(
    ID_AUTOMOVEL      SERIAL PRIMARY KEY,
    NR_ANO_FABRICACAO INT8        NOT NULL,
    NR_ANO_MODELO     INT8        NOT NULL,
    TP_COMBUSTIVEL    VARCHAR(50) NOT NULL,
    NR_PRECO          NUMERIC(10, 2),
    NR_KM_ATUAL       INT8        NOT NULL,
    ID_MODELO         INTEGER     NOT NULL,
    FOREIGN KEY (ID_MODELO) REFERENCES TBL_MODELO (ID_MODELO)
);