CREATE TABLE TBL_ACESSORIO
(
    ID_ACESSORIO SERIAL PRIMARY KEY,
    TX_DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE TBL_REL_AUTOMOVEL_ACESSORIO
(
    ID_AUTOMOVEL INTEGER NOT NULL,
    ID_ACESSORIO INTEGER NOT NULL,
    FOREIGN KEY (ID_AUTOMOVEL) REFERENCES TBL_AUTOMOVEL (ID_AUTOMOVEL),
    FOREIGN KEY (ID_ACESSORIO) REFERENCES TBL_ACESSORIO (ID_ACESSORIO)
);